-- Migração: Injeção Massiva de Trilhas Curriculares (Fase 2)
-- Aplicado via MCP em 2026-03-06
-- Total: 102 trilhas (Blocos A, B, C e D)

-- ========================================
-- BLOCO A: CICLO BÁSICO (axis='comum')
-- ========================================
INSERT INTO public.learning_trails 
(course_code, title, axis, category, excitation_level, credits_aula, credits_trabalho, is_experimental, program, prerequisites, status)
VALUES 
('4302111', 'Física I', 'comum', 'obrigatoria', 1, 6, 0, false, '["Cinemática vetorial", "Leis de Newton", "Trabalho e energia", "Sistemas de partículas", "Corpo rígido e momento angular"]', '{}', 'estavel'),
('4302113', 'Física Experimental I', 'comum', 'obrigatoria', 1, 4, 0, true, '["Metodologia científica", "Teoria de erros", "Instrumentação básica", "Análise de dados", "Relatórios científicos"]', '{}', 'estavel'),
('MAT2453', 'Cálculo Diferencial e Integral I', 'comum', 'obrigatoria', 1, 6, 0, false, '["Limites e Continuidade", "Derivadas e Aplicações", "Teorema Fundamental do Cálculo", "Técnicas de Integração", "Séries e Sequências"]', '{}', 'estavel'),
('MAT0112', 'Vetores e Geometria', 'comum', 'obrigatoria', 1, 4, 0, false, '["Vetores no plano e espaço", "Retas e planos", "Cônicas e quádricas", "Transformações lineares elementares"]', '{}', 'estavel'),
('4302112', 'Física II', 'comum', 'obrigatoria', 2, 6, 0, false, '["Gravitação", "Oscilações harmônicas", "Ondas em meios elásticos", "Estática e dinâmica de fluidos", "Termodinâmica"]', '{"4302111", "MAT2453"}', 'estavel'),
('4302114', 'Física Experimental II', 'comum', 'obrigatoria', 2, 4, 0, true, '["Mecânica dos fluidos", "Oscilações", "Ondas", "Calorimetria", "Termodinâmica"]', '{"4302113"}', 'estavel'),
('MAT2454', 'Cálculo Diferencial e Integral II', 'comum', 'obrigatoria', 2, 4, 0, false, '["Funções de várias variáveis", "Derivadas parciais", "Gradiente e otimização", "Integrais múltiplas", "Teoremas de cálculo vetorial"]', '{"MAT2453"}', 'estavel'),
('MAT0122', 'Álgebra Linear I', 'comum', 'obrigatoria', 2, 4, 0, false, '["Espaços vetoriais", "Bases e dimensão", "Transformações lineares", "Autovalores e autovetores", "Diagonalização"]', '{"MAT0112"}', 'estavel'),
('4302211', 'Física III', 'comum', 'obrigatoria', 3, 6, 0, false, '["Eletrostática", "Capacitância e dielétricos", "Corrente e resistência", "Circuitos CC", "Campo magnético"]', '{"4302112", "MAT2454", "MAT0112"}', 'estavel'),
('4302213', 'Física Experimental III', 'comum', 'obrigatoria', 3, 4, 0, true, '["Eletrostática", "Circuitos básicos", "Magnetismo", "Indução eletromagnética", "Medidas de precisão"]', '{"4302114"}', 'estavel'),
('MAT0216', 'Cálculo Diferencial e Integral III', 'comum', 'obrigatoria', 3, 6, 0, false, '["Integrais de linha", "Fluxo e Teorema de Gauss", "Teorema de Stokes", "Equações diferenciais de 1ª ordem", "Sistemas de EDOs"]', '{"MAT2454", "MAT0122"}', 'estavel'),
('MAC0115', 'Introdução à Computação', 'comum', 'obrigatoria', 3, 4, 0, false, '["Lógica de programação", "Estruturas de controle", "Funções e escopo", "Vetores e matrizes", "Algoritmos de busca e ordenação"]', '{}', 'estavel'),
('4302212', 'Física IV', 'comum', 'obrigatoria', 4, 6, 0, false, '["Indução Faraday", "Equações de Maxwell", "Ondas eletromagnéticas", "Óptica geométrica", "Interferência e difração"]', '{"4302211", "4302112"}', 'estavel'),
('4302214', 'Física Experimental IV', 'comum', 'obrigatoria', 4, 4, 0, true, '["Óptica", "Interferência", "Difração", "Radiação térmica", "Física moderna experimental"]', '{"4302213"}', 'estavel'),
('MAT0220', 'Cálculo Diferencial e Integral IV', 'comum', 'obrigatoria', 4, 4, 0, false, '["Sequências e séries de funções", "Séries de Fourier", "Transformada de Laplace", "Equações diferenciais parciais", "Introdução a variáveis complexas"]', '{"MAT0216"}', 'estavel'),
('MAP0214', 'Cálculo Numérico', 'comum', 'obrigatoria', 4, 4, 0, false, '["Zeros de funções", "Sistemas lineares", "Interpolação", "Integração numérica", "Resolução numérica de EDOs"]', '{"MAC0115"}', 'estavel')
ON CONFLICT (course_code) DO UPDATE SET title = EXCLUDED.title, excitation_level = EXCLUDED.excitation_level, credits_aula = EXCLUDED.credits_aula, credits_trabalho = EXCLUDED.credits_trabalho, is_experimental = EXCLUDED.is_experimental, program = EXCLUDED.program, prerequisites = EXCLUDED.prerequisites, axis = EXCLUDED.axis, category = EXCLUDED.category;

-- ========================================
-- BLOCO B: BACHARELADO (axis='bach')
-- ========================================
INSERT INTO public.learning_trails 
(course_code, title, axis, category, excitation_level, credits_aula, credits_trabalho, is_experimental, program, prerequisites, status)
VALUES 
('4302303', 'Eletromagnetismo I', 'bach', 'obrigatoria', 5, 4, 0, false, '["Eletrostática e meios materiais", "Magnetostática e campos na matéria", "Leis de Faraday e Indução", "Equações de Maxwell", "Ondas eletromagnéticas"]', '{"4302212", "MAT0216"}', 'estavel'),
('4302305', 'Mecânica I', 'bach', 'obrigatoria', 5, 4, 0, false, '["Princípios variacionais", "Equações de Lagrange", "Leis de conservação e Simetrias", "Equações de Hamilton", "Dinâmica de Corpo Rígido"]', '{"4302112", "MAT2454"}', 'estavel'),
('4302311', 'Física Quântica', 'bach', 'obrigatoria', 5, 4, 0, false, '["Radiação térmica e fótons", "Ondas de matéria de de Broglie", "Modelos atômicos e Bohr", "Equação de Schrödinger dependente do tempo", "Potenciais unidimensionais"]', '{"MAT0216", "4302212"}', 'estavel'),
('4302313', 'Física Experimental V', 'bach', 'obrigatoria', 5, 4, 0, true, '["Interferometria e Difração", "Óptica Geométrica e Física", "Polarização da luz", "Espectros atômicos", "Sensores ópticos"]', '{"4302214"}', 'estavel'),
('4302304', 'Eletromagnetismo II', 'bach', 'obrigatoria', 6, 4, 0, false, '["Guias de ondas e cavidades", "Radiação dipolar", "Espalhamento de radiação", "Relatividade restrita no Eletromagnetismo", "Potenciais de Liénard-Wiechert"]', '{"4302303"}', 'estavel'),
('4302306', 'Mecânica II', 'bach', 'obrigatoria', 6, 4, 0, false, '["Transformações canônicas", "Teoria de Hamilton-Jacobi", "Teoria de perturbações", "Mecânica de meios contínuos", "Introdução à Dinâmica de Fluídos"]', '{"4302305"}', 'estavel'),
('4302204', 'Física Matemática I', 'bach', 'obrigatoria', 6, 4, 0, false, '["Equações diferenciais parciais", "Problemas de condições de contorno", "Método de separação de variáveis", "Séries de Fourier", "Transformadas de Fourier e Laplace"]', '{"MAT2454"}', 'estavel'),
('4302314', 'Física Experimental VI', 'bach', 'obrigatoria', 6, 4, 0, true, '["Efeito Fotoelétrico", "Radiação de corpo negro", "Experimento de Franck-Hertz", "Raios-X e Difração de elétrons", "Efeito Zeeman"]', '{"4302313"}', 'estavel'),
('4302403', 'Mecânica Quântica I', 'bach', 'obrigatoria', 7, 4, 0, false, '["Espaço de Hilbert e Operadores", "Postulados da MQ", "Oscilador Harmônico", "Momento Angular e Spin", "Átomo de Hidrogênio"]', '{"4302311", "MAT0122", "4302204"}', 'estavel'),
('4302308', 'Termodinâmica', 'bach', 'obrigatoria', 7, 4, 0, false, '["Leis da Termodinâmica", "Potenciais termodinâmicos", "Relações de Maxwell", "Transições de fase", "Teorema de Nernst e 3ª Lei"]', '{"4302112"}', 'estavel'),
('4302307', 'Física Matemática II', 'bach', 'obrigatoria', 7, 4, 0, false, '["Funções de variável complexa", "Cálculo de resíduos", "Funções especiais (Bessel, Legendre)", "Funções de Green", "Aplicações em Física Avançada"]', '{"4302204"}', 'estavel'),
('4302401', 'Mecânica Estatística', 'bach', 'obrigatoria', 7, 4, 0, false, '["Ensemble Microcanônico", "Ensembles Canônico e Grande Canônico", "Gases de fótons e radiação", "Sistemas de bósons e férmions", "Cálculo de propriedades macroscópicas"]', '{"4302308", "4302305"}', 'estavel'),
('4302404', 'Mecânica Quântica II', 'bach', 'obrigatoria', 8, 4, 0, false, '["Teoria de Perturbação independente e dependente do tempo", "Método Variacional", "Aproximação WKB", "Teoria de Espalhamento", "Estrutura Fina e Efeito Stark"]', '{"4302403"}', 'estavel'),
('4302402', 'Laboratório de Física Avançada', 'bach', 'obrigatoria', 8, 8, 0, true, '["Ressonância Magnética Nuclear", "Efeito Mössbauer", "Física de Baixas Temperaturas", "Supercondutividade", "Física Nuclear Experimental"]', '{"4302314"}', 'estavel'),
('4300402', 'Introdução à Física do Estado Sólido', 'bach', 'eletiva', 8, 4, 0, false, '["Estrutura Cristalina e Rede Recíproca", "Vibrações da rede e fônons", "Gás de elétrons de Fermi", "Estrutura de bandas em sólidos", "Semicondutores e Propriedades Magnéticas"]', '{"4302403", "4302401"}', 'estavel'),
('4300378', 'Introdução à Física Nuclear e de Partículas', 'bach', 'eletiva', 8, 4, 0, false, '["Propriedades dos núcleos e decaimentos", "Modelos Nucleares", "Interação da radiação com a matéria", "Partículas elementares e Modelo Padrão", "Aceleradores e Detectores"]', '{"4302403"}', 'estavel')
ON CONFLICT (course_code) DO UPDATE SET title = EXCLUDED.title, excitation_level = EXCLUDED.excitation_level, credits_aula = EXCLUDED.credits_aula, credits_trabalho = EXCLUDED.credits_trabalho, is_experimental = EXCLUDED.is_experimental, program = EXCLUDED.program, prerequisites = EXCLUDED.prerequisites, axis = EXCLUDED.axis, category = EXCLUDED.category;

-- ========================================
-- BLOCO C: LICENCIATURA (axis='lic')
-- ========================================
INSERT INTO public.learning_trails 
(course_code, title, axis, category, excitation_level, credits_aula, credits_trabalho, is_experimental, program, prerequisites, status)
VALUES 
('4300151', 'Fundamentos de Mecânica', 'lic', 'obrigatoria', 1, 4, 0, false, '["Grandezas Físicas e Vetores", "Cinemática da Partícula", "Leis de Newton", "Trabalho e Energia Cinética", "Conservação da Energia"]', '{}', 'estavel'),
('4300157', 'Ciência, Educação e Linguagem', 'lic', 'obrigatoria', 1, 2, 1, false, '["Linguagem Científica e Escolar", "História da Ciência na Educação", "Argumentação no Ensino de Ciências", "Divulgação Científica", "Leitura e Escrita em Física"]', '{}', 'estavel'),
('4300160', 'Ótica', 'lic', 'obrigatoria', 1, 2, 1, true, '["Reflexão e Refração", "Espelhos e Lentes", "Ótica Geométrica", "Interferência e Difração", "Instrumentos Óticos"]', '{}', 'estavel'),
('4300152', 'Introdução às Medidas em Física', 'lic', 'obrigatoria', 2, 4, 0, true, '["Teoria de Erros e Incertezas", "Instrumentos de Medida", "Gráficos e Linearização", "Distribuições Estatísticas", "Relatórios Experimentais"]', '{}', 'estavel'),
('4300153', 'Mecânica', 'lic', 'obrigatoria', 2, 4, 1, false, '["Sistemas de Partículas", "Colisões e Momento Linear", "Rotações de Corpos Rígidos", "Torque e Momento Angular", "Equilíbrio Estático"]', '{"4300151"}', 'estavel'),
('4300156', 'Gravitação', 'lic', 'obrigatoria', 2, 2, 0, false, '["Leis de Kepler", "Lei da Gravitação Universal", "Potencial Gravitacional", "Órbita e Energia Orbital", "Noções de Cosmologia"]', '{"4300151"}', 'estavel'),
('EDM0402', 'Didática', 'lic', 'obrigatoria', 2, 4, 1, false, '["Teorias da Aprendizagem", "Planejamento Escolar", "Métodos de Ensino", "Avaliação Educacional", "Relação Professor-Aluno"]', '{}', 'estavel'),
('4300159', 'Física do Calor', 'lic', 'obrigatoria', 3, 4, 0, false, '["Temperatura e Calor", "Primeira e Segunda Lei da Termodinâmica", "Gases Ideais", "Teoria Cinética dos Gases", "Entropia"]', '{"4300151"}', 'estavel'),
('4300254', 'Laboratório de Mecânica', 'lic', 'obrigatoria', 3, 2, 0, true, '["Experimentos de Cinemática", "Dinâmica e Atrito", "Conservação de Energia Experimental", "Momento de Inércia", "Oscilações Mecânicas"]', '{"4300152", "4300153"}', 'estavel'),
('4300255', 'Mecânica dos Corpos Rígidos e dos Fluidos', 'lic', 'obrigatoria', 3, 4, 1, false, '["Tensores de Inércia", "Dinâmica de Rotação Avançada", "Estática dos Fluidos", "Dinâmica dos Fluidos", "Equações de Bernoulli e Continuidade"]', '{"4300153"}', 'estavel'),
('4300259', 'Termo-estatística', 'lic', 'obrigatoria', 4, 4, 1, false, '["Microestados e Macroestados", "Distribuição de Boltzmann", "Transições de Fase", "Estatísticas de Maxwell-Boltzmann", "Aplicações Estatísticas na Física"]', '{"4300159"}', 'estavel'),
('4300270', 'Eletricidade e Magnetismo I', 'lic', 'obrigatoria', 4, 4, 0, false, '["Carga Elétrica e Lei de Coulomb", "Campo Elétrico e Lei de Gauss", "Potencial Elétrico", "Capacitância e Dielétricos", "Corrente Elétrica e Resistência"]', '{"4300153"}', 'estavel'),
('4300356', 'Elementos e Estratégia para o Ensino de Física e Ciências', 'lic', 'obrigatoria', 4, 4, 1, false, '["Transposição Didática", "Experimentos de Baixo Custo", "Uso de Tecnologias no Ensino", "Seqüências de Ensino Investigativo", "PCN e BNCC de Física"]', '{"EDM0402"}', 'estavel'),
('4300271', 'Eletricidade e Magnetismo II', 'lic', 'obrigatoria', 5, 4, 1, false, '["Força Magnética e Campo Magnético", "Lei de Biot-Savart e Lei de Ampère", "Indução de Faraday e Lei de Lenz", "Circuitos AC", "Propriedades Magnéticas da Matéria"]', '{"4300270"}', 'estavel'),
('4300357', 'Oscilações e Ondas', 'lic', 'obrigatoria', 5, 2, 0, false, '["Oscilador Harmônico Simples", "Oscilações Amortecidas e Forçadas", "Equação de Onda", "Som e Ondas em Cordas", "Efeito Doppler"]', '{"4300153"}', 'estavel'),
('4300358', 'Propostas e Projetos para o Ensino de Física e Ciências', 'lic', 'obrigatoria', 5, 4, 1, false, '["Elaboração de Projetos Escolares", "Feiras de Ciências", "Interdisciplinaridade", "Avaliação de Projetos Educativos", "Ética na Pesquisa Educacional"]', '{"4300356"}', 'estavel'),
('4300373', 'Laboratório de Eletromagnetismo', 'lic', 'obrigatoria', 5, 4, 0, true, '["Mapeamento de Campo Elétrico", "Balança de Corrente", "Indução Eletromagnética Experimental", "Carga e Descarga de Capacitores", "Transformadores"]', '{"4300270", "4300152"}', 'estavel'),
('4300390', 'Práticas em Ensino de Física e Ciências', 'lic', 'obrigatoria', 5, 2, 3, false, '["Observação e Regência em Sala de Aula", "Desenvolvimento de Materiais Didáticos", "Práticas Experimentais Docentes", "Análise Crítica da Prática Escolar", "Relatório de Prática de Ensino"]', '{"4300356"}', 'estavel'),
('4300372', 'Eletromagnetismo', 'lic', 'obrigatoria', 6, 4, 0, false, '["Equações de Maxwell", "Ondas Eletromagnéticas no Vácuo", "Vetor de Poynting e Energia", "Radiação Eletromagnética", "Potenciais de Liénard-Wiechert"]', '{"4300271"}', 'estavel'),
('4300374', 'Relatividade', 'lic', 'obrigatoria', 6, 2, 1, false, '["Postulados da Relatividade Especial", "Transformações de Lorentz", "Dilatação do Tempo e Contração do Espaço", "Mecânica Relativística", "E=mc² e Energia de Repouso"]', '{"4300153"}', 'estavel'),
('4300377', 'Evidências Experimentais da Natureza Quântica', 'lic', 'obrigatoria', 6, 4, 0, true, '["Radiação de Corpo Negro", "Efeito Fotoelétrico", "Efeito Compton", "Espectros Atômicos", "Dualidade Onda-Partícula"]', '{"4300271", "4300373"}', 'estavel'),
('4300371', 'Introdução à Mecânica Quântica Ondulatória', 'lic', 'obrigatoria', 7, 4, 1, false, '["Equação de Schrödinger", "Poços de Potencial", "Oscilador Harmônico Quântico", "Átomo de Hidrogênio", "Spin e Princípio de Exclusão"]', '{"4300377", "4300357"}', 'estavel'),
('4300458', 'Complementos de Mecânica Clássica', 'lic', 'obrigatoria', 7, 4, 0, false, '["Mecânica Lagrangiana", "Mecânica Hamiltoniana", "Pequenas Oscilações", "Vínculos e Coordenadas Generalizadas", "Sistemas não-Inerciais"]', '{"4300255"}', 'estavel'),
('EDM0425', 'Metodologia do Ensino de Física I', 'lic', 'obrigatoria', 7, 4, 3, false, '["História do Ensino de Física", "Conceitos de Epistemologia da Ciência", "Estratégias de Resolução de Problemas", "Laboratórios Didáticos no Ensino Médio", "Análise de Livros Didáticos"]', '{"4300356"}', 'estavel'),
('MFT0964', 'Língua Brasileira de Sinais', 'lic', 'obrigatoria', 7, 4, 2, false, '["Cultura Surda e Identidade", "Gramática Básica de Libras", "Vocabulário do Cotidiano e Científico", "Legislação e Educação Especial", "Práticas de Interpretação"]', '{}', 'estavel'),
('EDM0426', 'Metodologia do Ensino de Física II', 'lic', 'obrigatoria', 8, 4, 3, false, '["Ensino de Física Moderna", "Cultura Científica e Sociedade", "Aulas de Campo e Museus", "Temáticas Atuais do Ensino de Física", "Trabalho de Conclusão de Curso Docente"]', '{"EDM0425"}', 'estavel')
ON CONFLICT (course_code) DO UPDATE SET title = EXCLUDED.title, excitation_level = EXCLUDED.excitation_level, credits_aula = EXCLUDED.credits_aula, credits_trabalho = EXCLUDED.credits_trabalho, is_experimental = EXCLUDED.is_experimental, program = EXCLUDED.program, prerequisites = EXCLUDED.prerequisites, axis = EXCLUDED.axis, category = EXCLUDED.category;

-- ========================================
-- BLOCO C (cont.): FÍSICA MÉDICA (axis='med')
-- ========================================
INSERT INTO public.learning_trails 
(course_code, title, axis, category, excitation_level, credits_aula, credits_trabalho, is_experimental, program, prerequisites, status)
VALUES 
('MDR0632', 'Introdução à Física Médica', 'med', 'obrigatoria', 2, 2, 0, false, '["História da Física Médica", "Áreas de Atuação Profissional", "Conceitos Básicos de Radiobiologia", "Organização Hospitalar", "Ética na Física Médica"]', '{}', 'estavel'),
('MDR0633', 'Elementos de Anatomia e Fisiologia Humana', 'med', 'obrigatoria', 2, 4, 0, false, '["Sistema Esquelético e Muscular", "Sistema Cardiovascular e Respiratório", "Sistema Nervoso e Endócrino", "Fisiologia Celular e Biofísica", "Anatomia Radiográfica"]', '{}', 'estavel'),
('MDR0635', 'Estatística Médica I', 'med', 'obrigatoria', 3, 4, 0, false, '["Bioestatística e Probabilidade", "Testes de Hipóteses Médicas", "Análise de Correlação e Regressão", "Curvas de Sobrevivência", "Epidemiologia Quantitativa"]', '{}', 'estavel'),
('MDR0634', 'Informática Médica e Saúde Digital', 'med', 'obrigatoria', 4, 4, 0, false, '["Sistemas de Informação em Saúde", "Pruontuário Eletrônico", "Padrão DICOM e PACS", "Telemedicina", "Inteligência Artificial na Saúde"]', '{}', 'estavel'),
('4300325', 'Física do Corpo Humano', 'med', 'obrigatoria', 5, 4, 0, false, '["Biomecânica e Dinâmica Esquelética", "Biofísica dos Fluidos Circulatórios", "Processos de Transporte no Corpo", "Termodinâmica Biológica", "Bioeletricidade"]', '{"4302112", "MAT2454"}', 'estavel'),
('MDR0637', 'Diagnóstico por Imagens Médicas', 'med', 'obrigatoria', 5, 4, 0, false, '["Técnicas de Radiodiagnóstico", "Tomografia Computadorizada", "Ressonância Magnética", "Ultrassonografia Médica", "Introdução à Medicina Nuclear"]', '{"4302212"}', 'estavel'),
('MDR0639', 'Física do Diagnóstico por imagens I', 'med', 'obrigatoria', 5, 4, 0, false, '["Física da Produção de Raios-X", "Interação da Radiação com a Matéria", "Qualidade da Imagem Radiográfica", "Dosimetria em Radiodiagnóstico", "Sistemas de Detecção de Radiação"]', '{"4302212"}', 'estavel'),
('4300436', 'Efeitos Biológicos das Radiações', 'med', 'obrigatoria', 6, 4, 0, false, '["Mecanismos Celulares de Dano por Radiação", "Efeitos Estocásticos e Radioindução", "Efeitos Determinísticos e Síndromes Radiais", "Cinética de Reparo de DNA", "Relação Dose-Resposta Biológica"]', '{"MDR0633"}', 'estavel'),
('4302305_MED', 'Mecânica I (Física Médica)', 'med', 'obrigatoria', 6, 4, 0, false, '["Cinemática em 3D", "Dinâmica de Sistemas de Partículas", "Oscilações Mecânicas Avançadas", "Forças Centrais e Órbitas", "Sistemas de Referência não Inerciais"]', '{"4302112", "MAT0216"}', 'estavel'),
('4302311_MED', 'Física Quântica (Física Médica)', 'med', 'obrigatoria', 6, 2, 0, false, '["Física Moderna e Átomo de Bohr", "Equação de Schrödinger 1D", "Potenciais de Barreira e Tunelamento", "Modelos Atômicos de Muitos Elétrons", "Radiação e Matéria em Escala Microscópica"]', '{"4302212"}', 'estavel'),
('4300437', 'Física das Radiações I', 'med', 'obrigatoria', 7, 6, 0, false, '["Física Nuclear Básica", "Cinética de Decaimento Radioativo", "Interação de Partículas Carregadas e Fótons", "Fontes Radioativas na Medicina", "Teoria da Cavidade e Dosimetria"]', '{"4302311"}', 'estavel'),
('MDR0640', 'Proteção Radiológica I', 'med', 'obrigatoria', 7, 4, 0, false, '["Normas da CNEN e Vigilância Sanitária", "Cálculo de Blindagens Médicas", "Monitoração Individual e de área", "Plano de Proteção Radiológica Hospitalar", "Gerenciamento de Rejeitos Radioativos"]', '{"MDR0639"}', 'estavel'),
('4300439', 'Laboratório de Dosimetria das Radiações', 'med', 'obrigatoria', 8, 4, 0, true, '["Calibração de Câmaras de Ionização", "Medidas de Kerma e Dose Absorvida", "Dosimetria Termoluminescente (TLD)", "Contadores Geiger-Müller e Cintilação", "Garantia de Qualidade em Dosimetria"]', '{"4300437"}', 'estavel'),
('MDR0641', 'Medicina Nuclear', 'med', 'obrigatoria', 8, 4, 0, false, '["Radiofármacos e Marcadores", "Física da Câmara Gama e SPECT", "Física do PET-CT", "Dosimetria Interna em Medicina Nuclear", "Controle de Qualidade em Equipamentos de Medicina Nuclear"]', '{"4300437"}', 'estavel'),
('MDR0642', 'Radioterapia', 'med', 'obrigatoria', 8, 4, 0, false, '["Aceleradores Lineares Médicos", "Braquiterapia Física", "Planejamento de Tratamento Computadorizado", "Distribuição de Dose em Radioterapia", "Protocolos de Dosimetria Clínica"]', '{"4300437"}', 'estavel'),
('MDR0643', 'Física do Diagnóstico por Imagens II', 'med', 'obrigatoria', 8, 4, 0, false, '["Física da Ressonância Magnética", "Física do Ultrassom", "Processamento Digital de Imagens Médicas", "Segurança em Ambientes de RM", "Aplicações de Contraste e Doppler"]', '{"MDR0639"}', 'estavel'),
('MDR0644', 'Introdução ao Ambiente Hospitalar', 'med', 'obrigatoria', 8, 2, 0, false, '["Gestão da Qualidade Hospitalar", "Biossegurança e Controle de Infecção", "Rotinas e Fluxos Hospitalares", "Segurança do Paciente", "Tecnologia em Saúde e Sustentabilidade"]', '{"MDR0632"}', 'estavel'),
('MDR0645', 'Introdução à Saúde Ocupacional, Medicina Legal e Ética da Física Médica', 'med', 'obrigatoria', 9, 4, 0, false, '["Legislação do Trabalho e Perícias", "Ética no Atendimento Médico-Hospitalar", "Saúde do Profissional da Física Médica", "Responsabilidade Civil do Físico Médico", "Códigos de Ética Profissional"]', '{"MDR0640"}', 'estavel'),
('MDR0646', 'Tópicos Avançados de Matemática e Física em Medicina', 'med', 'obrigatoria', 9, 4, 0, false, '["Simulações Monte Carlo na Física Médica", "Processamento Avançado de Sinais Médicos", "Modelagem Numérica em Radiobiologia", "Biofotônica", "Nanomedicina e Física"]', '{"4302305", "4302303"}', 'estavel'),
('MDR0647', 'Estágio Hospitalar Geral', 'med', 'obrigatoria', 9, 0, 4, false, '["Prática em Proteção Radiológica", "Acompanhamento Técnico em Diagnóstico", "Rotinas de Medicina Nuclear e Radioterapia", "Relatório de Atividades Hospitalares", "Interação Multidisciplinar Clínica"]', '{"MDR0640", "MDR0641", "MDR0642"}', 'estavel'),
('MDR0660', 'Prática Profissional em Imagens Médicas', 'med', 'obrigatoria', 10, 0, 5, false, '["Execução de Protocolos de CQ em Imagem", "Análise de Imagens para Diagnóstico", "Gestão de Sistemas de Aquisição", "Otimização de Dose em Radiologia", "Seminários de Prática Clínica"]', '{"MDR0647"}', 'estavel'),
('MDR0661', 'Prática Profissional em Radioterapia', 'med', 'obrigatoria', 10, 0, 5, false, '["Dosimetria em Aceleradores Lineares", "Verificação de Planos e IMRT", "Gestão de Segurança em Radioterapia", "Controle de Qualidade em Braquiterapia", "Apresentação de Casos Clínicos"]', '{"MDR0647"}', 'estavel')
ON CONFLICT (course_code) DO UPDATE SET title = EXCLUDED.title, excitation_level = EXCLUDED.excitation_level, credits_aula = EXCLUDED.credits_aula, credits_trabalho = EXCLUDED.credits_trabalho, is_experimental = EXCLUDED.is_experimental, program = EXCLUDED.program, prerequisites = EXCLUDED.prerequisites, axis = EXCLUDED.axis, category = EXCLUDED.category;

-- ========================================
-- BLOCO D: OPTATIVAS & ELETIVAS
-- ========================================
INSERT INTO public.learning_trails 
(course_code, title, axis, category, excitation_level, credits_aula, credits_trabalho, is_experimental, program, prerequisites, status)
VALUES 
('AGA0319', 'Relatividade Geral e Aplicações Astrofísicas', 'bach', 'eletiva', 7, 4, 0, false, '["Relatividade restrita e mecânica relativística", "Gravidade e geometria do espaço-tempo", "Espaços-tempos curvos e geodésicas", "Buracos negros de Schwarzschild e Kerr", "Ondas gravitacionais"]', '{"4302305"}', 'estavel'),
('4300430', 'Cosmologia Física', 'bach', 'eletiva', 8, 4, 0, false, '["Modelo cosmológico padrão", "Expansão do universo e Lei de Hubble", "Nucleossíntese primordial", "Radiação Cósmica de Fundo", "Energia escura e matéria escura"]', '{"4302403"}', 'estavel'),
('AGA0293', 'Astrofísica Estelar', 'bach', 'eletiva', 7, 4, 0, false, '["Estrutura e evolução estelar", "Nucleossíntese em estrelas", "Diagrama HR e classificação espectral", "Anãs brancas e estrelas de nêutrons", "Supernovas e elementos pesados"]', '{"4302212"}', 'estavel'),
('AGA0299', 'Astrofísica Galáctica', 'bach', 'eletiva', 8, 4, 0, false, '["Estrutura da Via Láctea", "Populações estelares e meio interestelar", "Dinâmica galáctica", "Galáxias ativas e quasares", "Formação e evolução de galáxias"]', '{"AGA0293"}', 'estavel'),
('4300441', 'Detectores de Radiação', 'bach', 'eletiva', 7, 4, 0, false, '["Detectores a gás (Geiger-Müller)", "Detectores de cintilação", "Detectores semicondutores", "Fotodetectores e CCDs", "Eletrônica de aquisição de dados"]', '{"4302212"}', 'estavel'),
('4300405', 'Evolução dos Conceitos da Física', 'bach', 'eletiva', 5, 4, 0, false, '["Física aristotélica e medieval", "Revolução copernicana e mecânica newtoniana", "Termodinâmica e eletromagnetismo no séc XIX", "Relatividade e mecânica quântica", "Física contemporânea e fronteiras"]', '{}', 'estavel'),
('4300420', 'Introdução à Física de Plasmas', 'bach', 'eletiva', 8, 4, 0, false, '["Conceitos fundamentais de plasmas", "Equações de movimento de partículas carregadas", "Ondas em plasmas", "Confinamento magnético e Tokamaks", "Aplicações tecnológicas de plasmas"]', '{"4302303", "4302305"}', 'estavel'),
('4300410', 'Óptica Não-Linear', 'bach', 'eletiva', 8, 4, 0, false, '["Polarização não-linear e susceptibilidade", "Geração de segundo harmônico", "Efeito Kerr óptico", "Espalhamento Raman estimulado", "Aplicações em lasers e telecomunicações"]', '{"4302303"}', 'estavel'),
('4300415', 'Física Computacional', 'bach', 'eletiva', 6, 4, 0, false, '["Métodos de Monte Carlo", "Dinâmica molecular", "Resolução numérica de EDPs", "Simulação de sistemas quânticos", "Visualização científica e análise de dados"]', '{"MAC0115", "4302212"}', 'estavel'),
('4300425', 'Introdução à Teoria Quântica de Campos', 'bach', 'eletiva', 9, 4, 0, false, '["Quantização canônica do campo escalar", "Campo de Dirac e spinores", "Eletrodinâmica quântica (QED)", "Diagramas de Feynman", "Renormalização e grupo de renormalização"]', '{"4302404"}', 'estavel'),
('4300435', 'Supercondutividade e Superfluídez', 'bach', 'eletiva', 9, 4, 0, false, '["Fenomenologia da supercondutividade", "Teoria BCS", "Efeito Josephson", "Supercondutores de alta temperatura", "Superfluídez do Hélio líquido"]', '{"4302403", "4302401"}', 'estavel'),
('4300445', 'Aprendizado de Máquina para Física', 'bach', 'eletiva', 8, 4, 0, false, '["Regressão e classificação", "Redes neurais e deep learning", "Análise de dados experimentais com ML", "Simulações assistidas por IA", "Aplicações em física de partículas e materiais"]', '{"MAC0115"}', 'estavel'),
('4300450', 'Física de Semicondutores', 'bach', 'eletiva', 8, 4, 0, false, '["Estrutura de bandas em semicondutores", "Portadores de carga e dopagem", "Junção p-n e diodos", "Transistores e dispositivos optoeletrônicos", "Nanodispositivos e LEDs"]', '{"4300402"}', 'estavel'),
('4300455', 'Caracterização de Materiais', 'bach', 'eletiva', 8, 4, 0, true, '["Difração de Raios-X e estrutura cristalina", "Microscopia eletrônica (SEM, TEM)", "Espectroscopia Raman e Infravermelho", "Microscopia de Força Atômica (AFM)", "Análise térmica e calorimetria"]', '{"4302212"}', 'estavel'),
('4300465', 'Evolução dos Conceitos da Física (Lic)', 'lic', 'eletiva', 6, 4, 0, false, '["Gênese do pensamento científico", "Newton e a mecânica clássica", "Eletromagnetismo e termodinâmica no séc XIX", "Crise da física clássica", "Construção da física moderna"]', '{}', 'estavel'),
('4300470', 'Divulgação Científica e Ensino de Física', 'lic', 'eletiva', 7, 2, 2, false, '["Museus e centros de ciência", "Mídias digitais na divulgação", "Produção de material de divulgação", "Comunicação pública da ciência", "Física para não-físicos"]', '{}', 'estavel'),
('4300475', 'Processos Criativos no Ensino', 'lic', 'eletiva', 7, 2, 2, false, '["Criatividade e inovação educacional", "Design thinking aplicado ao ensino", "Gamificação na sala de aula", "Projetos STEAM", "Teatro e arte na educação científica"]', '{"EDM0402"}', 'estavel'),
('4300480', 'Física e Sociedade', 'lic', 'eletiva', 5, 2, 0, false, '["Ciência, Tecnologia e Sociedade (CTS)", "Impactos ambientais da energia nuclear", "Ética na pesquisa científica", "Política científica no Brasil", "Física e sustentabilidade"]', '{}', 'estavel'),
('MDR0650', 'Aceleradores de Partículas na Medicina', 'med', 'eletiva', 9, 4, 0, false, '["Princípios de aceleração de partículas", "Cíclotrons e síncrotrons médicos", "Terapia com prótons e íons pesados", "Produção de radioisótopos para PET", "Dosimetria em hadronterapia"]', '{"4300437"}', 'estavel'),
('MDR0655', 'Sala Limpa e Nanotecnologia Médica', 'med', 'eletiva', 9, 4, 0, true, '["Protocolos de sala limpa", "Fabricação de microdispositivos", "Nanopartículas para diagnóstico", "Teranóstica e nanomedicina", "Controle de qualidade em nanofabricação"]', '{"MDR0633"}', 'estavel'),
('5910186', 'Biofísica I', 'med', 'eletiva', 6, 4, 0, false, '["Termodinâmica de sistemas biológicos", "Transporte através de membranas", "Eletrofisiologia", "Estrutura de biomoléculas", "Bioenergética celular"]', '{"4302112"}', 'estavel'),
('4300485', 'Partículas Elementares para Leigos', 'bach', 'livre', 3, 2, 0, false, '["O que são partículas elementares", "O Modelo Padrão simplificado", "O Bóson de Higgs", "Aceleradores de partículas: como funcionam", "Mistérios não resolvidos da física"]', '{}', 'estavel')
ON CONFLICT (course_code) DO UPDATE SET title = EXCLUDED.title, excitation_level = EXCLUDED.excitation_level, credits_aula = EXCLUDED.credits_aula, credits_trabalho = EXCLUDED.credits_trabalho, is_experimental = EXCLUDED.is_experimental, program = EXCLUDED.program, prerequisites = EXCLUDED.prerequisites, axis = EXCLUDED.axis, category = EXCLUDED.category;
